// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using usf_asgmt3_api.Integration.LocalDataRepo;

namespace usf_asgmt3_api.Migrations
{
    [DbContext(typeof(LocalDBContext))]
    [Migration("20190325041918_Initial-DB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("usf_asgmt3_api.model.Company", b =>
                {
                    b.Property<string>("ticker")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cik");

                    b.Property<string>("industry_category");

                    b.Property<string>("lei");

                    b.Property<long?>("market_cap");

                    b.Property<string>("name");

                    b.HasKey("ticker");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("usf_asgmt3_api.model.Company_Detail", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEO");

                    b.Property<string>("companyName");

                    b.Property<string>("description");

                    b.Property<string>("exchange");

                    b.Property<string>("industry");

                    b.Property<string>("issueType");

                    b.Property<string>("sector");

                    b.Property<string>("website");

                    b.HasKey("symbol");

                    b.ToTable("Company_Details");
                });

            modelBuilder.Entity("usf_asgmt3_api.model.Company_Dividend", b =>
                {
                    b.Property<string>("symbol");

                    b.Property<string>("exDate");

                    b.Property<float>("amount");

                    b.Property<string>("declaredDate");

                    b.Property<string>("flag");

                    b.Property<string>("indicated");

                    b.Property<string>("paymentDate");

                    b.Property<string>("qualified");

                    b.Property<string>("recordDate");

                    b.Property<string>("type");

                    b.HasKey("symbol", "exDate");

                    b.ToTable("Company_Dividends");
                });

            modelBuilder.Entity("usf_asgmt3_api.model.Price", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("adj_close");

                    b.Property<float>("adj_high");

                    b.Property<float>("adj_low");

                    b.Property<float>("adj_open");

                    b.Property<int>("adj_volume");

                    b.Property<float>("close");

                    b.Property<string>("date");

                    b.Property<string>("frequency");

                    b.Property<float>("high");

                    b.Property<bool>("intraperiod");

                    b.Property<float>("low");

                    b.Property<float>("open");

                    b.Property<string>("ticker");

                    b.Property<int>("volume");

                    b.HasKey("id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("usf_asgmt3_api.model.Symbol", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("date");

                    b.Property<string>("iexId");

                    b.Property<bool>("isEnabled");

                    b.Property<string>("name");

                    b.Property<string>("type");

                    b.HasKey("symbol");

                    b.ToTable("Symbols");
                });
#pragma warning restore 612, 618
        }
    }
}
